### ISSUE TITLE
Error on default starting

### ISSUE THREAD

**Issue by bloodbare** [plone/guillotina_cms#14]
```guillotina_1     | Unable to close spurious connection
guillotina_1     | Traceback (most recent call last):
guillotina_1     |   File "/usr/local/lib/python3.7/site-packages/guillotina/db/transaction_manager.py", line 77, in begin
guillotina_1     |     await self._close_txn(txn)
guillotina_1     |   File "/usr/local/lib/python3.7/site-packages/guillotina/db/transaction_manager.py", line 125, in _close_txn
guillotina_1     |     await self._storage.close(txn._db_conn)
guillotina_1     |   File "/usr/local/lib/python3.7/site-packages/guillotina/db/storages/pg.py", line 556, in close
guillotina_1     |     asyncio.wait_for(self._pool.release(con, timeout=1), 1))
guillotina_1     |   File "/usr/local/lib/python3.7/asyncio/tasks.py", line 412, in wait_for
guillotina_1     |     return fut.result()
guillotina_1     |   File "/usr/local/lib/python3.7/site-packages/asyncpg/pool.py", line 643, in release
guillotina_1     |     return await asyncio.shield(ch.release(timeout), loop=self._loop)
guillotina_1     |   File "/usr/local/lib/python3.7/site-packages/asyncpg/pool.py", line 214, in release
guillotina_1     |     raise ex
guillotina_1     |   File "/usr/local/lib/python3.7/site-packages/asyncpg/pool.py", line 204, in release
guillotina_1     |     await self._con.reset(timeout=budget)
guillotina_1     |   File "/usr/local/lib/python3.7/site-packages/asyncpg/connection.py", line 1081, in reset
guillotina_1     |     await self.execute(reset_query, timeout=timeout)
guillotina_1     |   File "/usr/local/lib/python3.7/site-packages/asyncpg/connection.py", line 273, in execute
guillotina_1     |     return await self._protocol.query(query, timeout)
guillotina_1     |   File "asyncpg/protocol/protocol.pyx", line 317, in query
guillotina_1     |   File "asyncpg/protocol/protocol.pyx", line 675, in asyncpg.protocol.protocol.BaseProtocol._check_state
guillotina_1     | asyncpg.exceptions._base.InterfaceError: cannot perform operation: another operation is in progress
elasticsearch    | [2018-09-26T20:36:23,297][WARN ][o.e.d.c.ParseField       ] Deprecated field [_retry_on_conflict] used, expected [retry_on_conflict] instead
guillotina_1     | Error on execution of view 499f501b83a842aebd35d4ac73d6ec72
guillotina_1     | Traceback (most recent call last):
guillotina_1     |   File "/usr/local/lib/python3.7/site-packages/guillotina/traversal.py", line 274, in handler
guillotina_1     |     view_result = await self.view()
guillotina_1     |   File "/usr/local/lib/python3.7/site-packages/guillotina/configure/__init__.py", line 462, in __call__
guillotina_1     |     return await func(self.context, self.request)
guillotina_1     |   File "/usr/local/lib/python3.7/site-packages/guillotina/api/behaviors.py", line 160, in default_get
guillotina_1     |     result[name] = await schema_serializer()
guillotina_1     |   File "/usr/local/lib/python3.7/site-packages/guillotina/json/serialize_schema.py", line 86, in __call__
guillotina_1     |     return self.serialize()
guillotina_1     |   File "/usr/local/lib/python3.7/site-packages/guillotina/json/serialize_schema.py", line 93, in serialize
guillotina_1     |     self.schema_json['properties'][name] = serializer.serialize()
guillotina_1     |   File "/usr/local/lib/python3.7/site-packages/guillotina/json/serialize_schema_field.py", line 108, in serialize
guillotina_1     |     text = json_compatible(value)
guillotina_1     |   File "/usr/local/lib/python3.7/site-packages/guillotina/json/serialize_value.py", line 31, in json_compatible
guillotina_1     |     ' {0!r} ({1}) JSON compatible.'.format(value, type(value)))
guillotina_1     | TypeError: No converter for making <guillotina_cms.vocabularies.source.AppSettingSource object at 0x7f26aea4ee48> (<class 'guillotina_cms.vocabularies.source.AppSettingSource'>) JSON compatible.
guillotina_1     | Error bulk putting: {'took': 57, 'errors': True, 'items': [{'update': {'_index': 'plone-db-container_1', '_type': 'doc', '_id': '6024a4c14f434c0fa81b120a625c15cd', 'status': 404, 'error': {'type': 'document_missing_exception', 'reason': '[doc][6024a4c14f434c0fa81b120a625c15cd]: document missing', 'index_uuid': 't-ZYA2sHSdiW6AbBLhu0qQ', 'shard': '1', 'index': 'plone-db-container_1'}}}]}
guillotina_1     | Error on execution of view 101dfda0502147a18d2c517adf55157e
guillotina_1     | Traceback (most recent call last):
guillotina_1     |   File "/usr/local/lib/python3.7/site-packages/guillotina/traversal.py", line 274, in handler
guillotina_1     |     view_result = await self.view()
guillotina_1     |   File "/usr/local/lib/python3.7/site-packages/guillotina/configure/__init__.py", line 462, in __call__
guillotina_1     |     return await func(self.context, self.request)
guillotina_1     |   File "/usr/local/lib/python3.7/site-packages/guillotina/api/behaviors.py", line 166, in default_get
guillotina_1     |     result[name] = await schema_serializer()
guillotina_1     |   File "/usr/local/lib/python3.7/site-packages/guillotina/json/serialize_schema.py", line 86, in __call__
guillotina_1     |     return self.serialize()
guillotina_1     |   File "/usr/local/lib/python3.7/site-packages/guillotina/json/serialize_schema.py", line 93, in serialize
guillotina_1     |     self.schema_json['properties'][name] = serializer.serialize()
guillotina_1     |   File "/usr/local/lib/python3.7/site-packages/guillotina/json/serialize_schema_field.py", line 108, in serialize
guillotina_1     |     text = json_compatible(value)
guillotina_1     |   File "/usr/local/lib/python3.7/site-packages/guillotina/json/serialize_value.py", line 31, in json_compatible
guillotina_1     |     ' {0!r} ({1}) JSON compatible.'.format(value, type(value)))
guillotina_1     | TypeError: No converter for making <guillotina_cms.vocabularies.source.AppSettingSource object at 0x7f26aea4ee48> (<class 'guillotina_cms.vocabularies.source.AppSettingSource'>) JSON compatible.```

**Comment by vangheem** [comment]
ES isn't working for me either with setup in the README:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 822, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 943, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 930, in create_connection
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 475, in sock_connect
    return await fut
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 9200)
```

**Comment by vangheem** [comment]
Fixed "TypeError: No converter" in latest
